<section class="panel compact-panel">
    <div class="panel-header">
        <h1>Reset Password</h1>
        <div class="panel-meta">Use the secure reset link generated by the system.</div>
    </div>

    <form method="post" action="<?= e(url('/reset-password')) ?>" class="form-grid compact-form">
        <?= \App\Helpers\Csrf::input() ?>
        <input type="hidden" name="selector" value="<?= e($selector ?? '') ?>">
        <input type="hidden" name="token" value="<?= e($token ?? '') ?>">
        <label class="field">
            <span>New Password</span>
            <input type="password" name="password" autocomplete="new-password" required>
        </label>
        <label class="field">
            <span>Confirm Password</span>
            <input type="password" name="password_confirmation" autocomplete="new-password" required>
        </label>
        <div class="login-hint">Use a passphrase or a long password. Minimum 12 characters.</div>
        <div class="form-actions">
            <button class="btn btn-primary" type="submit">Reset Password</button>
            <a class="btn" href="<?= e(url('/login')) ?>">Back to Sign In</a>
        </div>
    </form>
</section>
