<?php

declare(strict_types=1);

return [
    'up' => [
        'CREATE TABLE IF NOT EXISTS customer_receivable_items (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            branch_id INT UNSIGNED NOT NULL,
            booking_reference VARCHAR(50) NOT NULL,
            service_line_reference VARCHAR(50) NULL,
            due_group VARCHAR(50) NOT NULL DEFAULT "service_sale",
            currency CHAR(3) NOT NULL,
            due_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            allocated_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            outstanding_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            due_date DATE NULL,
            status ENUM("open", "partially_paid", "paid", "cancelled") NOT NULL DEFAULT "open",
            remarks TEXT NULL,
            created_by_user_id INT UNSIGNED NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            KEY idx_customer_receivable_items_branch (branch_id),
            KEY idx_customer_receivable_items_booking (booking_reference),
            KEY idx_customer_receivable_items_service_line (service_line_reference),
            KEY idx_customer_receivable_items_status (status),
            CONSTRAINT fk_customer_receivable_items_branch FOREIGN KEY (branch_id) REFERENCES branches (id),
            CONSTRAINT fk_customer_receivable_items_user FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'CREATE TABLE IF NOT EXISTS customer_receipts (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            branch_id INT UNSIGNED NOT NULL,
            booking_reference VARCHAR(50) NOT NULL,
            receipt_no VARCHAR(50) NOT NULL UNIQUE,
            receipt_date DATE NOT NULL,
            currency CHAR(3) NOT NULL,
            received_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            allocated_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            unallocated_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            payment_method ENUM("cash", "bank_transfer", "debit_card", "credit_card") NOT NULL,
            reference_number VARCHAR(100) NULL,
            bank_card_detail VARCHAR(190) NULL,
            charges_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            status ENUM("received", "partially_allocated", "fully_allocated", "void") NOT NULL DEFAULT "received",
            exchange_rate_to_booking DECIMAL(18,8) NULL,
            remarks TEXT NULL,
            created_by_user_id INT UNSIGNED NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            KEY idx_customer_receipts_branch (branch_id),
            KEY idx_customer_receipts_booking (booking_reference),
            KEY idx_customer_receipts_date (receipt_date),
            KEY idx_customer_receipts_status (status),
            CONSTRAINT fk_customer_receipts_branch FOREIGN KEY (branch_id) REFERENCES branches (id),
            CONSTRAINT fk_customer_receipts_user FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'CREATE TABLE IF NOT EXISTS customer_receipt_allocations (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            customer_receipt_id BIGINT UNSIGNED NOT NULL,
            customer_receivable_item_id BIGINT UNSIGNED NOT NULL,
            allocated_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            allocation_note VARCHAR(190) NULL,
            exchange_rate_used DECIMAL(18,8) NULL,
            allocated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by_user_id INT UNSIGNED NULL,
            KEY idx_customer_receipt_allocations_receipt (customer_receipt_id),
            KEY idx_customer_receipt_allocations_receivable (customer_receivable_item_id),
            CONSTRAINT fk_customer_receipt_allocations_receipt FOREIGN KEY (customer_receipt_id) REFERENCES customer_receipts (id) ON DELETE CASCADE,
            CONSTRAINT fk_customer_receipt_allocations_receivable FOREIGN KEY (customer_receivable_item_id) REFERENCES customer_receivable_items (id) ON DELETE CASCADE,
            CONSTRAINT fk_customer_receipt_allocations_user FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    ],
    'down' => [
        'DROP TABLE IF EXISTS customer_receipt_allocations',
        'DROP TABLE IF EXISTS customer_receipts',
        'DROP TABLE IF EXISTS customer_receivable_items',
    ],
];
