<?php

declare(strict_types=1);

return [
    'up' => [
        'CREATE TABLE IF NOT EXISTS booking_services (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            booking_id BIGINT UNSIGNED NOT NULL,
            branch_id INT UNSIGNED NOT NULL,
            line_reference VARCHAR(50) NOT NULL,
            display_order INT UNSIGNED NOT NULL DEFAULT 0,
            service_type ENUM("air ticket", "visa", "umrah", "hotel", "transport", "tourism", "other") NOT NULL,
            supplier_id INT UNSIGNED NULL,
            supplier_name_snapshot VARCHAR(190) NULL,
            currency CHAR(3) NOT NULL,
            sale_price DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            purchase_cost DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            taxes DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            vat DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            commission DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            service_charge DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            due_date DATE NULL,
            service_status VARCHAR(50) NOT NULL DEFAULT "Open",
            remarks TEXT NULL,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            created_by_user_id INT UNSIGNED NULL,
            updated_by_user_id INT UNSIGNED NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uniq_booking_services_booking_line (booking_id, line_reference),
            KEY idx_booking_services_booking (booking_id),
            KEY idx_booking_services_branch (branch_id),
            KEY idx_booking_services_type (service_type),
            KEY idx_booking_services_supplier (supplier_id),
            KEY idx_booking_services_currency (currency),
            KEY idx_booking_services_active (is_active),
            CONSTRAINT fk_booking_services_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
            CONSTRAINT fk_booking_services_branch FOREIGN KEY (branch_id) REFERENCES branches (id),
            CONSTRAINT fk_booking_services_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE SET NULL,
            CONSTRAINT fk_booking_services_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
            CONSTRAINT fk_booking_services_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users (id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'CREATE TABLE IF NOT EXISTS service_air_ticket (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            booking_service_id BIGINT UNSIGNED NOT NULL,
            pnr VARCHAR(50) NULL,
            ticket_number VARCHAR(50) NULL,
            airline VARCHAR(120) NULL,
            sector_from VARCHAR(120) NULL,
            sector_to VARCHAR(120) NULL,
            departure_date DATE NULL,
            return_date DATE NULL,
            travel_class VARCHAR(50) NULL,
            fare DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            ticket_tax DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            ticket_vat DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            ticket_commission DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            supplier_cost DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            sale_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
            ticket_remarks TEXT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uniq_service_air_ticket_service (booking_service_id),
            CONSTRAINT fk_service_air_ticket_service FOREIGN KEY (booking_service_id) REFERENCES booking_services (id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'CREATE TABLE IF NOT EXISTS service_visa (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            booking_service_id BIGINT UNSIGNED NOT NULL,
            visa_country VARCHAR(120) NULL,
            visa_type VARCHAR(120) NULL,
            remarks TEXT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uniq_service_visa_service (booking_service_id),
            CONSTRAINT fk_service_visa_service FOREIGN KEY (booking_service_id) REFERENCES booking_services (id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'CREATE TABLE IF NOT EXISTS service_umrah (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            booking_service_id BIGINT UNSIGNED NOT NULL,
            package_name VARCHAR(190) NULL,
            remarks TEXT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uniq_service_umrah_service (booking_service_id),
            CONSTRAINT fk_service_umrah_service FOREIGN KEY (booking_service_id) REFERENCES booking_services (id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'CREATE TABLE IF NOT EXISTS service_hotel (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            booking_service_id BIGINT UNSIGNED NOT NULL,
            hotel_name VARCHAR(190) NULL,
            city VARCHAR(120) NULL,
            remarks TEXT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uniq_service_hotel_service (booking_service_id),
            CONSTRAINT fk_service_hotel_service FOREIGN KEY (booking_service_id) REFERENCES booking_services (id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'CREATE TABLE IF NOT EXISTS service_transport (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            booking_service_id BIGINT UNSIGNED NOT NULL,
            transport_mode VARCHAR(120) NULL,
            route_notes VARCHAR(190) NULL,
            remarks TEXT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uniq_service_transport_service (booking_service_id),
            CONSTRAINT fk_service_transport_service FOREIGN KEY (booking_service_id) REFERENCES booking_services (id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'CREATE TABLE IF NOT EXISTS service_tour (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            booking_service_id BIGINT UNSIGNED NOT NULL,
            tour_name VARCHAR(190) NULL,
            destination VARCHAR(120) NULL,
            remarks TEXT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uniq_service_tour_service (booking_service_id),
            CONSTRAINT fk_service_tour_service FOREIGN KEY (booking_service_id) REFERENCES booking_services (id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'CREATE TABLE IF NOT EXISTS service_other (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            booking_service_id BIGINT UNSIGNED NOT NULL,
            label VARCHAR(190) NULL,
            remarks TEXT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uniq_service_other_service (booking_service_id),
            CONSTRAINT fk_service_other_service FOREIGN KEY (booking_service_id) REFERENCES booking_services (id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    ],
    'down' => [
        'DROP TABLE IF EXISTS service_other',
        'DROP TABLE IF EXISTS service_tour',
        'DROP TABLE IF EXISTS service_transport',
        'DROP TABLE IF EXISTS service_hotel',
        'DROP TABLE IF EXISTS service_umrah',
        'DROP TABLE IF EXISTS service_visa',
        'DROP TABLE IF EXISTS service_air_ticket',
        'DROP TABLE IF EXISTS booking_services',
    ],
];
