<?php

declare(strict_types=1);

return [
    'up' => [
        'CREATE TABLE IF NOT EXISTS booking_documents (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            branch_id INT UNSIGNED NOT NULL,
            booking_id BIGINT UNSIGNED NOT NULL,
            traveler_id BIGINT UNSIGNED NULL,
            booking_service_id BIGINT UNSIGNED NULL,
            customer_receipt_id BIGINT UNSIGNED NULL,
            supplier_payment_id BIGINT UNSIGNED NULL,
            supplier_obligation_id BIGINT UNSIGNED NULL,
            document_type ENUM("passport_copy", "visa_copy", "ticket_copy", "payment_proof", "supplier_invoice", "general_attachment") NOT NULL,
            title VARCHAR(190) NOT NULL,
            notes TEXT NULL,
            original_file_name VARCHAR(255) NOT NULL,
            stored_file_name VARCHAR(255) NOT NULL,
            storage_disk VARCHAR(50) NOT NULL DEFAULT "local",
            storage_path VARCHAR(500) NOT NULL,
            mime_type VARCHAR(120) NOT NULL,
            file_extension VARCHAR(20) NOT NULL,
            file_size_bytes BIGINT UNSIGNED NOT NULL,
            sha256_hash CHAR(64) NOT NULL,
            visibility ENUM("private") NOT NULL DEFAULT "private",
            status ENUM("active", "superseded", "revoked") NOT NULL DEFAULT "active",
            replaced_document_id BIGINT UNSIGNED NULL,
            uploaded_by_user_id INT UNSIGNED NULL,
            updated_by_user_id INT UNSIGNED NULL,
            revoked_by_user_id INT UNSIGNED NULL,
            revoked_at DATETIME NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            KEY idx_booking_documents_branch (branch_id),
            KEY idx_booking_documents_booking (booking_id),
            KEY idx_booking_documents_traveler (traveler_id),
            KEY idx_booking_documents_service (booking_service_id),
            KEY idx_booking_documents_receipt (customer_receipt_id),
            KEY idx_booking_documents_supplier_payment (supplier_payment_id),
            KEY idx_booking_documents_supplier_obligation (supplier_obligation_id),
            KEY idx_booking_documents_type (document_type),
            KEY idx_booking_documents_status (status),
            KEY idx_booking_documents_hash (sha256_hash),
            CONSTRAINT fk_booking_documents_branch FOREIGN KEY (branch_id) REFERENCES branches (id),
            CONSTRAINT fk_booking_documents_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
            CONSTRAINT fk_booking_documents_traveler FOREIGN KEY (traveler_id) REFERENCES travelers (id) ON DELETE SET NULL,
            CONSTRAINT fk_booking_documents_service FOREIGN KEY (booking_service_id) REFERENCES booking_services (id) ON DELETE SET NULL,
            CONSTRAINT fk_booking_documents_receipt FOREIGN KEY (customer_receipt_id) REFERENCES customer_receipts (id) ON DELETE SET NULL,
            CONSTRAINT fk_booking_documents_supplier_payment FOREIGN KEY (supplier_payment_id) REFERENCES supplier_payments (id) ON DELETE SET NULL,
            CONSTRAINT fk_booking_documents_supplier_obligation FOREIGN KEY (supplier_obligation_id) REFERENCES supplier_obligations (id) ON DELETE SET NULL,
            CONSTRAINT fk_booking_documents_replaced_document FOREIGN KEY (replaced_document_id) REFERENCES booking_documents (id) ON DELETE SET NULL,
            CONSTRAINT fk_booking_documents_uploaded_by FOREIGN KEY (uploaded_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
            CONSTRAINT fk_booking_documents_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
            CONSTRAINT fk_booking_documents_revoked_by FOREIGN KEY (revoked_by_user_id) REFERENCES users (id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    ],
    'down' => [
        'DROP TABLE IF EXISTS booking_documents',
    ],
];
